name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches:
      - main
      - next
  merge_group:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# # You can leverage Vercel Remote Caching with Turbo to speed up your builds
# # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
# env:
#   FORCE_COLOR: 3
#   TURBO_TEAM: ${{ vars.TURBO_TEAM }}
#   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run tests
        run: pnpm test

      - name: Prettier check
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: TypeScript check
        run: pnpm typecheck
